### ISSUE TITLE
New display: Almost nothing visible

### ISSUE THREAD

**Issue by richardklingler** [sparkfun/Flexible_Grayscale_OLED#3]
New display arrived from Digikey....

Hooked up with Arduino Uno....only the right most vertical line is brighter...
the rest is extremely dark and isn't visible in daylight.

I assume those OLEDs don't last very long...

So stay away if you still consider buying this thing.....pretty expensive for a almost-DOA product..

**Comment by nseidle** [comment]
Sounds like the driver board is working but you got a bad or damaged display. These are fragile and can be damaged if bent too far. I'm sure Digikey will help you get a replacement. If not certainly let SparkFun CS know.
